/**
 * Phase 3 fixture corpus: >=30 synthetic real-world list phrasings, each with
 * its expected parse (fixtures/list-phrasings/phrasings.fixture.json). Every
 * record asserts the FULL projected structure — product type, quantity, unit,
 * pack count, dimensions, material, color, ruling, brand requirement, scope,
 * durability, optionality, hard constraints, candidates, ambiguity flags,
 * review routing — plus per-field confidences, so any parser behavior change
 * that alters meaning fails here first.
 *
 * The expected values were generated by running the parser once and
 * hand-verifying every record against the phrasing's plain meaning, then
 * frozen; they are regression anchors, not tautologies.
 */
import { describe, expect, it } from "vitest";
import { provenanceDefect } from "../src/ingestion/provenance";
import { parsePasteIntake } from "../src/parsing";
import type {
  AmbiguityFlag,
  ParseOutcome,
  PiiCategory,
} from "../src/parsing";
import type { RequirementScope } from "../src/contracts";
import { loadFixtureDoc } from "./helpers/fixtures";

interface CorpusItem {
  lineNumber: number;
  productTypeSlug: string | null;
  quantity: number;
  unit: string;
  packCount: number | null;
  dimensions: string | null;
  material: string | null;
  color: string | null;
  rulingStyle: string | null;
  brandRequirement: string;
  requiredBrandSlug: string | null;
  scope: RequirementScope;
  durability: string | null;
  optionality: string;
  prohibitedSubstitutions: readonly string[];
  productCandidates: readonly string[];
  ambiguityFlags: readonly AmbiguityFlag[];
  needsReview: boolean;
  fieldConfidences: Readonly<Record<string, number>>;
}

interface CorpusRecord {
  id: string;
  phrasing: string;
  expected: {
    skippedLineCount: number;
    redactionCategories: readonly PiiCategory[];
    items: CorpusItem[];
  };
}

const doc = loadFixtureDoc<CorpusRecord>("list-phrasings/phrasings.fixture.json");
const clock = () => Date.parse("2026-08-04T12:00:00.000Z");

const parseRecord = (record: CorpusRecord): ParseOutcome =>
  parsePasteIntake(
    { intakeId: `corpus-${record.id}`, text: record.phrasing },
    { clock, fixtureSet: doc.fixtureSet },
  );

/** The exact projection frozen in the fixture's expected items. */
const project = (outcome: ParseOutcome): CorpusItem[] =>
  outcome.items.map((i) => ({
    lineNumber: i.lineNumber,
    productTypeSlug: i.draft.productTypeSlug,
    quantity: i.draft.quantity,
    unit: i.draft.unit,
    packCount: i.draft.packCount,
    dimensions: i.draft.dimensions,
    material: i.draft.material,
    color: i.draft.color,
    rulingStyle: i.draft.rulingStyle,
    brandRequirement: i.draft.brandRequirement,
    requiredBrandSlug: i.draft.requiredBrandSlug,
    scope: i.draft.scope,
    durability: i.draft.durability,
    optionality: i.draft.optionality,
    prohibitedSubstitutions: i.draft.prohibitedSubstitutions,
    productCandidates: i.productCandidates,
    ambiguityFlags: i.ambiguityFlags,
    needsReview: i.needsReview,
    fieldConfidences: i.fieldConfidences,
  }));

describe("list-phrasings corpus (Phase 3 acceptance)", () => {
  it("holds at least 30 distinct labeled phrasings", () => {
    expect(doc.records.length).toBeGreaterThanOrEqual(30);
    expect(new Set(doc.records.map((r) => r.id)).size).toBe(doc.records.length);
    expect(new Set(doc.records.map((r) => r.phrasing)).size).toBe(
      doc.records.length,
    );
  });

  it.each(doc.records.map((r) => [r.id, r] as const))(
    "%s parses to its expected structure",
    (_id, record) => {
      const outcome = parseRecord(record);
      expect(outcome.review.skippedLineCount).toBe(
        record.expected.skippedLineCount,
      );
      expect(outcome.redaction.categoriesHit).toEqual(
        record.expected.redactionCategories,
      );
      expect(project(outcome)).toEqual(record.expected.items);
    },
  );

  it("populates per-field confidence in (0, 1] on every parsed item", () => {
    for (const record of doc.records) {
      for (const item of parseRecord(record).items) {
        const entries = Object.entries(item.fieldConfidences);
        expect(entries.length, `${record.id}: empty confidences`).toBeGreaterThan(0);
        // Core extraction fields are always scored, even when unknown.
        for (const key of ["quantity", "unit", "optionality", "sourceConfidence"]) {
          expect(
            item.fieldConfidences[key],
            `${record.id}: missing confidence for ${key}`,
          ).toBeTypeOf("number");
        }
        for (const [key, value] of entries) {
          expect(value, `${record.id}.${key} out of range`).toBeGreaterThan(0);
          expect(value, `${record.id}.${key} out of range`).toBeLessThanOrEqual(1);
        }
      }
    }
  });

  it("carries complete fixture-labeled provenance on every item (SS1.4)", () => {
    for (const record of doc.records) {
      for (const item of parseRecord(record).items) {
        expect(provenanceDefect(item.provenance)).toBeNull();
        expect(item.provenance.sourceType).toBe("fixture");
        expect(item.provenance.source).toBe(doc.fixtureSet);
        expect(item.draft.sourceKind).toBe("fixture");
        expect(item.provenance.confidence).toBe(item.draft.sourceConfidence);
      }
    }
  });

  it("demands user confirmation on every corpus parse (SS1.5)", () => {
    for (const record of doc.records) {
      const outcome = parseRecord(record);
      expect(outcome.review.requiresUserConfirmation).toBe(true);
      expect(outcome.review.itemsNeedingReview).toBe(
        record.expected.items.filter((i) => i.needsReview).length,
      );
    }
  });

  it("covers the ambiguity surface: review-routed and clean records both exist", () => {
    const flat = doc.records.flatMap((r) => r.expected.items);
    expect(flat.filter((i) => i.needsReview).length).toBeGreaterThanOrEqual(5);
    expect(flat.filter((i) => !i.needsReview).length).toBeGreaterThanOrEqual(20);
    expect(
      flat.filter((i) => i.prohibitedSubstitutions.length > 0).length,
    ).toBeGreaterThanOrEqual(8);
  });
});
